Refactor makeConfig.m
andreassommer/ifdiff pull request #16
Opened 2024-07-16 19:42 UTC by Schlevidon

## Summary
Refactoring of the `makeConfig` function which is used to store constants in IFDIFF. 
Added comments, removed unused constants, fixed inconsistencies, renamed some variables and changed their values.

## Changelog
- Completely removed special handling of `iif` (ternary if) from IFDIFF. This mechanism was previously intended for a now very niche use case, where a RHS contained a user-authored function called `iif` that implemented a ternary conditional operator in MATLAB. Now this functionality has become fairly obsolete, since:
    - MATLAB does not have its own ternary if implementation, so this mechanism would only be used by a very small subset of users who define their own as a function specifically called `iif`.
    - Even if a user were to write such a custom function, it can simply be treated like any other helper function, that contains switches, by IFDIFF. No special treatment is required!
- Various name changes that hopefully make some constants a bit more self-explanatory. However, feedback is still very much welcome!
- Removed many constants that were used in the past, but not anymore.
- Added comments to split the config into two sections: One that contains parameters which may be changed depending on the specific problem a user is facing and another which only contains constants related to IFDIFFs internal implementation. This will become more important once we add handling for Filippov systems, since these may require problem specific settings from a user.
- Fixed inconsistencies where some constants in the config were unintentionally hard-coded in other places of the code.
- Some formatting changes to make the code look prettier and more readable.
- Added a RHS function to the test folder which contains all functions that are treated in a special way by IFDIFF (if, abs, max, min, sign, helper functions). This RHS can be used to examine how changes in the config affect the naming of variables in the preprocessed function.

2024-07-17 14:36 UTC, LemongrabThree commented on test/TestMakeConfig/special_function_calls_rhs.m
Can you add a test case for this, please?

2024-07-17 14:37 UTC, LemongrabThree requested changes
test case missing for `special_function_calls_rhs.m`

2024-07-23 09:46 UTC, LemongrabThree approved these changes

2024-07-23 15:34 UTC, Schlevidon commented on test/TestMakeConfig/special_function_calls_rhs.m
Added a test case. ✔️

2024-07-23 17:05 UTC, merged