State Jumps
andreassommer/ifdiff pull request #23
Opened 2024-10-08 09:27 UTC by LemongrabThree

IFDIFF can now handle switches with state updates (Delta ~= 0)

2024-11-09 21:05 UTC, LemongrabThree commented
Ready and rebased onto public.

2024-11-18 15:38 UTC, Schlevidon requested changes
Amazing work overall, but we do have a couple of issues that need to be fixed before we merge:
- Critical: Fix the broken test case and speedtracker benchmark
- High Priority: Put some safety measures in place for the ignore mechanism only going one function call deep.
- Some minor code and documentation issues

Also, not sure if we actually need it, but I think adding a small section about state jumps into the README would be nice.

2024-11-18 15:38 UTC, Schlevidon commented on ComputeSensitivities/VDE_RHS_p.m
>     % dG = VDE_RHS_p(sol, functionRHS_simple, t, G, parameters, options)
Outdated comment

2024-11-18 15:38 UTC, Schlevidon commented on ComputeSensitivities/VDE_RHS_y.m
>     % dG = VDE_RHS_y(sol, functionRHS_simple, t, G, parameters, options)
Outdated comment

2024-11-18 15:38 UTC, Schlevidon commented on ComputeSensitivities/generateSensitivityFunction.m
>     if olHasOption(varargin, 'integrator'),                 integrator = olGetOption(varargin, 'integrator'); end
Could simplify this by using olGetOption with a default value (e.g. `option = olGetOption(varargin, 'option_name', default)`. Very much an optional change though, so its also fine if it stays like this for now.

2024-11-18 15:38 UTC, Schlevidon commented on ComputeSensitivities/getGy_Gp_update.m
> +    % Updates = generateGmatrices_Updates(datahandle, amountG, modelNum, Gp_flag, options)
Outdated comment

2024-11-18 15:38 UTC, Schlevidon commented on Examples/subway/newYorkCityExampleIntegrationForThesis.m
> +% swindices = datanyc.variable.switchingIndices;
Changed by accident

2024-11-18 15:38 UTC, Schlevidon commented on getJumpIndices_getJumpConditions.m
> +function jumps = getJumpIndices_getJumpConditions(datahandle)
Would be cleaner to directly pass the mtrees as function arguments instead of the whole datahandle

2024-11-18 15:38 UTC, Schlevidon commented on getJumpIndices_getJumpConditions.m
> +% helper functions. Return a 3xN array whose first row is the row index (of the call expression) is the
The comment describing the rows of the output has a mistake

2024-11-18 15:38 UTC, Schlevidon commented on initDatahandleFields.m
> +
Unnecessary blank lines at the end

2024-11-18 15:38 UTC, Schlevidon commented on mtree_replaceIfByCtrlif.m
> +function [mtreeobj, ctrlif_index] = mtree_replaceIfByCtrlif(mtreeobj, ctrlif_index, ignore)
The argument `ignore` should be `ignores` (or some other shared name) for consistency with the other functions (see `mtree_replace[Abs/Max/Min/Sign]ByCtrlif`)

2024-11-18 15:38 UTC, Schlevidon commented on preprocess_adjustFcnCallsRhs.m
> +        if ismembertol(rIndex_Fcn_i.Fname(j), ignored)
Shouldn't it be `ismember` instead of `ismembertol`?

2024-11-18 15:38 UTC, Schlevidon commented on preprocess_fcnInRhs.m
> +    occursUnignored(i) = ~all(ismembertol(callsInRhs, preprocessed.rhs{4, 1}));
Shouldn't it be `ismember` instead of `ismembertol`?

2024-11-18 15:38 UTC, Schlevidon commented on preprocess_fcnInRhs.m
> +        allOccurrencesIgnored = all(ismembertol(callsInFcn, fcn{4, i}));
Shouldn't it be `ismember` instead of `ismembertol`?

2024-11-18 15:38 UTC, Schlevidon commented on preprocess_fcnInRhs.m
> +% meaning, if f and g both contain no ctrlif, but g calls a function h that does, then too bad.
This seems scary. Maybe we should create an issue, so we remember to fix this in the future. We could also print a warning message when a function is excluded from preprocessing due to this mechanism.

2024-11-18 15:38 UTC, Schlevidon commented on speedtracker/benchmarks/expBenchmark.m
Why was this benchmark removed?

2024-11-18 15:38 UTC, Schlevidon commented on speedtracker/benchmarks/twoJumpsGoodRHS.m
> +    ifdiff_jumpif(x, -1, -1);
Outdated benchmark, `ifdiff_jumpif` only accepts two arguments now.

2024-11-18 15:38 UTC, Schlevidon commented on preprocess_adjustFcnCallsRhs.m
> +        rIndex_Fcn_i = rIndex_Fcn_i.(Fname);
⚠️ CRITICAL: Moving lines 24,26,27 into the inner loop (over `j`) breaks the `TestPreprocessing` test case.  The problem seems to occur whenever there are two or more calls to the same helper function in the source code (e.g. in `test/TestPreprocessing/testPreprocessingRHS.m`). 

After moving these lines back into the outer loop (over `i`) all test cases pass. However, I'm not sure whether or not this change would have any other unwanted consequences.

2024-11-23 12:29 UTC, LemongrabThree commented on initDatahandleFields.m
> +
you noticed that on this one file only?

2024-11-23 12:35 UTC, LemongrabThree commented on preprocess_fcnInRhs.m
> +% meaning, if f and g both contain no ctrlif, but g calls a function h that does, then too bad.
Yeah, nothing works in general with three levels of function calls. I'm creating an issue.

2024-11-23 12:39 UTC, LemongrabThree commented on speedtracker/benchmarks/expBenchmark.m
I think I found it too basic or something? Not sure, I guess I'll add it back.

2024-11-23 15:24 UTC, LemongrabThree commented on preprocess_adjustFcnCallsRhs.m
> +        rIndex_Fcn_i = rIndex_Fcn_i.(Fname);
Thanks for the tip, moving those lines out (with some other tweaks) turned out to be the solution.

2024-11-24 10:51 UTC, Schlevidon approved these changes

2024-11-24 10:54 UTC, merged